## Create Mira

POST http://localhost:3003/v1/miras
Content-Type: application/json

{
    "userId": "4d09629c-1c2f-46b3-8b86-c0c410181274",
    "gender": "male",
    "profession": "Software Developer",
    "yearExperience": 4,
    "biography": "some biography",
    "birthdate": "2024-01-15T13:23:16.655+00:00",
    "educationLevel": "universityEducation"
}

###
GET http://localhost:3003/v1
