@hostname = localhost
@port = 3001
@host = {{hostname}}:{{port}}/v1
@contentType = application/json

### Mira
### Create Mira
POST http://{{host}}/miras
Content-Type: {{contentType}}

{
    "userId": "936381cb-3a44-4692-b52e-ba302db628f7",
    "gender": "male",
    "profession": "Software Developer",
    "yearExperience": 4,
    "address": {
        "street": "123 Main St",
        "city": "New York",
        "country": "NY"
    },
    "biography": "some biography",
    "birthdate": "2024-01-15T13:23:16.655+00:00",
    "educationLevel": "university"
}

### Get Mira by User
GET http://{{host}}/miras/936381cb-3a44-4692-b52e-ba302db628f7/users

### Get Mira
GET http://{{host}}/miras/3ba2c9e1-6c4c-425a-8893-8ab6385e57ce

### List all Miras
GET http://{{host}}/miras?page=2&perPage=1

### Shared a mira profile
GET http://{{host}}/miras/3ba2c9e1-6c4c-425a-8893-8ab6385e57ce/shared


### Update Mira
PATCH  http://{{host}}/miras/3ba2c9e1-6c4c-425a-8893-8ab6385e57ce
Content-Type: {{contentType}}

{
    "gender": "male",
    "profession": "Software Developer",
    "yearExperience": 4,
    "address": {
        "street": "123 Main St",
        "city": "New York",
        "country": "NY"
    },
    "biography": "some biography",
    "birthdate": "2024-01-15T13:23:16.655+00:00",
    "educationLevel": "university",
    "isWork": true,
    "isFreelancer": true
}

#### Careers Module #####

### Create a new career
POST http://{{host}}/careers
Content-Type: {{contentType}}

{
    "miraId": "92c9a6a1-e609-441a-b3cf-293b7288aa26",
    "companyId": "f1375f71-1884-4d13-a21e-99de4e44bc19",
    "positionId": "41a04bbc-4db2-4d59-8330-082c9870d41e",
    "title": "Mid Frontend Developer",
    "description": "some description",
    "location": "Luanda, Angola",
    "locationType": "in-person",
    "employmentType": "full-time",
    "startYear": "2023-08-28",
    "isShow": true,
    "isCurrent": true,
    "isVerified": false
}

### Update a new career
PATCH  http://{{host}}/careers/3bc30d28-4730-4e23-a22e-93cedba412a3
Content-Type: {{contentType}}

{
    "miraId": "92c9a6a1-e609-441a-b3cf-293b7288aa26",
    "title": "Mid Backend Developer",
    "description": "some description",
    "location": "Luanda, Angola",
    "locationType": "in-person",
    "employmentType": "full-time",
    "startYear": "2023-08-28",
    "isShow": true,
    "isCurrent": true,
    "isVerified": false
}

### List all Careers
GET http://{{host}}/careers/92c9a6a1-e609-441a-b3cf-293b7288aa26?perPage=2